### ISSUE TITLE
.codeconfig candidates

### ISSUE THREAD

**Issue by begedin** [coderly/code#18]
Looking at commands we have at the moment, there are several assumptions about the team's development process that we make, which would be good candidates for configurable settings in a `.codeconfig` file.
# `publish`/`pr`

We currently assume the pull request is being made against the `development` branch, with an optional switch to make it against the `master` branch. 

We could go further than that and allow the user to specify primary and alternative branches for the pull request to be made against. We could then have something like 
- `code pr`
- `code pr --alternative`

Optionally, we could allow the option to specify the name of the branch to make a pull request against, with the default being `development` (or a configured branch name).
# `ready`

`ready` assumes the label for the awaiting review state is `awaiting review`. We could make this a configurable setting.

Also, we could potentially allow a `code label <label_name>` command.
# `hotfix`/`fix`

Assumes the prefix for a hotfix branch is `hotfix`. This could be configurable as well.

**Comment by venkatd** [comment]
@begedin these all look like good ideas. Can you create separate tasks for these? I think in terms of `code hotfix` and `code label` we an hold off on implementing those.

**Comment by begedin** [comment]
Made the tasks in Asana
- [Allow configurable primary and alternative branch to make a PR against using 'code publish'](https://app.asana.com/0/42067882888954/42231027022024)
- [Allow configurable label for 'code ready' command](https://app.asana.com/0/42067882888954/42231027022027)
- [Allow configurable prefix for a hotfix branch](https://app.asana.com/0/42067882888954/42231027022030)
